# Generated by Django 5.2.14 on 2026-05-24 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('scope', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_label', models.CharField(blank=True, default='', max_length=255)),
                ('activity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('activity_unit', models.CharField(blank=True, default='', max_length=50)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('normalized_unit', models.CharField(blank=True, default='', max_length=50)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('calculated_emissions', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('employee', models.CharField(blank=True, default='', max_length=255)),
                ('extra_normalized', models.JSONField(blank=True, default=dict)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('flagged', 'Flagged'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='organizations.organization')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='records_nor_organiz_f26a1b_idx'), models.Index(fields=['datasource'], name='records_nor_datasou_dee7e2_idx'), models.Index(fields=['raw_record'], name='records_nor_raw_rec_858fe7_idx')],
            },
        ),
    ]
